"""
visualiser.py

Portfolio visualisation for stakeholder presentations.

Creates:
  - Allocation bar chart (optimal weights per stock)
  - Efficient frontier with optimal portfolio marked

"""

import matplotlib.pyplot as plt
import numpy as np
from typing import List

def plot_allocation(weights: np.ndarray,
                    tickers: List[str],
                    output_path: str = 'outputs/plots/allocation.png'):
  
  """
  Creates a bar chart showing optimal portfolio weights per stock.

  Args:
    weights:      Optimal weights, shape (n,)
    tickers:      Ticker symbols, length n
    output_path:  Where to save the PNG
  
  """
  fig, ax = plt.subplots(figsize=(10, 6))

  bars = ax.bar(tickers, weights, color='steelblue', alpha=0.75, edgecolor='black', linewidth=0.8)

  # Add percentage labels on top of each bar
  # Portfolio managers need exact numbers, not just visual proportions
  for bar in bars:
    height = bar.get_height()
    ax.text(bar.get_x() + bar.get_width() / 2.0,
            height + 0.005,
            f'{height:.1%}',
            ha='center', va='bottom', fontsize=11, fontweight='bold')
    ax.set_ylabel('Portfolio Weight', fontsize=12)
    ax.set_xlabel('FTSE 100 Stock', fontsize=12)
    ax.set_title('Optimal Portfolio Allocation (FCA Compliant - No Short Selling)', fontsize=13, fontweight='bold')
    ax.set_ylim(0, max(weights) * 1.2)  # 20% headroom above tallest bar
    ax.axhline(y=0, color='black', linewidth=0.5)
    ax.grid(axis='y', alpha=0.3, linestyle='--')

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches='tight')
    plt.close()
    print(f'Allocation chart saved: {output_path}')

def plot_efficient_frontier(expected_returns: np.ndarray,
                            cov_matrix: np.ndarray,
                            optimal_weights: np.ndarray,
                            risk_free_rate: float,
                            output_path: str = 'outputs/plots/efficient_frontier.png'):
  """
  Plot the efficient frontier with the optimal portfolio marked.

  The frontier is generated by solving the optimisation at 50 evenly-spaced target return levels
  between the minimum and maximum achievable returns.

  Args:
    expected_returns: Annualised mean returns, shape (n,)
    cov_matrix:       Annualised covariance matrix, shape (n, n)
    optimal_weights:  Weights of the specific portfolio to highlight
    risk_free_rate:   UK gilt rate for Capital Market Line
    output_path:      Where to save the PNG
  
  """

  # Import here to avoid circular imports (visualiser imports from optimiser)
  from optimizer import optimise_portfolio, portfolio_return, portfolio_variance

  # --- Generate the efficient frontier curve ---
  # Solve at 50 target return levels: fine enough for a smooth curve,
  # Coarse enough to run in a few seconds.
  min_ret = float(expected_returns.min())
  max_ret = float(expected_returns.max())
  target_returns = np.linspace(min_ret, max_ret, 50)

  frontier_vols = []
  frontier_returns = []

  for target in target_returns:
    try:
      result = optimise_portfolio(expected_returns, cov_matrix, target, allow_short_selling = False)

      if result['success']:
        frontier_returns.append(result['expected_return'])
        frontier_vols.append(result['volatility'])
    
    except Exception:
      # Some target returns near the boundary may be infeasible - skip them
      continue

  # --- Build the plot ---
  fig, ax = plt.subplots(figsize=(12, 8))

  # Efficient frontier curve
  ax.plot(frontier_vols, frontier_returns, 'b-', linewidth=2.5, label='Efficient Frontier', zorder=3)

  # Individual assets (each stock at its own risk/return point)
  asset_vols = [np.sqrt(cov_matrix[i, i]) for i in range(len(expected_returns))]
  ax.scatter(asset_vols, expected_returns, s=120, c='grey', alpha=0.7, zorder=4, label='Individual Stocks')

  # Label each individual stock
  from data_loader import load_config
  try:
    config = load_config()
    labels = config['tickers']
  
  except Exception:
    labels = [f'Asset {i+1}' for i in range (len(expected_returns))]
  for i, label in enumerate(labels):
    ax.annotate(label, (asset_vols[i], expected_returns[i]), textcoords='offset points', xytext=(6, 4), fontsize=9)

  # Optimal portfolio (red star)
  opt_ret = portfolio_return(optimal_weights, expected_returns)
  opt_vol = np.sqrt(portfolio_variance(optimal_weights, cov_matrix))
  ax.scatter(opt_vol, opt_ret, s=350, c='red', marker='*', edgecolors='darkred', linewidths=1.5,
             zorder=6, label=f'Optimal Portfolio ({opt_ret:.1%} return)')
  # Capital Market Line (from risk-free rate through optimal portfolio)
  # Shows the best possible risk/return trade-off including the risk-free asset
  cml_vols = np.linspace(0, max(frontier_vols) * 1.1, 100)
  sharpe = (opt_ret - risk_free_rate) / opt_vol
  cml_rets = risk_free_rate + sharpe * cml_vols
  ax.plot(cml_vols, cml_rets, 'g--', linewidth=1.5, label=f'Capital Market Line (Sharpe= {sharpe:.2f})', alpha=0.7)

  # Risk-free rate on y-axis
  ax.axhline(y=risk_free_rate, color='green', linewidth=1, linestyle=':',
             alpha=0.6, label=f'Risk-free rate ({risk_free_rate:.1%})')
  
  ax.set_xlabel('Portfolio Volatility (Annualised Std Dev)', fontsize=12)
  ax.set_ylabel('Expected Return )Annualised', fontsize=12)
  ax.set_title('Efficient Frontier - FTSE 100 Portfolio Optimisation\n''Minimum Variance Frontier (No Short Selling, FCA Compliant)',
               fontsize=13, fontweight='bold')
  ax.yaxis.set_major_formatter(plt.FuncFormatter(lambda y, _: f'{y:.0%}'))
  ax.xaxis.set_major_formatter(plt.FuncFormatter(lambda x, _: f'{x:.0%}'))
  ax.legend(loc='lower right', fontsize=10)
  ax.grid(True, alpha=0.3, linestyle='--')
  plt.tight_layout()
  plt.savefig(output_path, dpi=300, bbox_inches='tight')
  plt.close()
  print(f'Efficient frontier saved: {output_path}')
